### ISSUE TITLE
Fix AssetInfo after update to go-bindata-assetfs

### ISSUE THREAD

**Issue by boonep** [divan/gobenchui#7]
Panic due to go-bindata-assetfs API update

related to elazarl/go-bindata-assetfs#23

Example error output:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
    panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7e904e]
goroutine 6499 [running]:
testing.tRunner.func1(0xc82150c5a0)
    /usr/local/go/src/testing/testing.go:450 +0x171
github.com/elazarl/go-bindata-assetfs.(*AssetFS).Open(0xc821e0bef0, 0xc82164e2b0, 0xf, 0x0, 0x0, 0x0, 0x0)
    /home/travis/gopath/src/github.com/elazarl/go-bindata-assetfs/assetfs.go:148 +0x22e
net/http.serveFile(0x2b9f5b923f80, 0xc821f980a0, 0xc8217a9880, 0x2b9f5b954b88, 0xc821e0bef0, 0xdfd190, 0x1, 0xdfd201)
    /usr/local/go/src/net/http/fs.go:394 +0x5b1
```

**Comment by divan** [comment]
Thanks for spotting this! PR applied.
